//! Generate the "All shortcodes" section of `docs/authoring/emoji.md`.
//!
//! The Emoji column holds the *bare* shortcode (`:rocket:`) — the compiler
//! converts it to the character at build time, so the rendered table doubles
//! as a self-test: a row that stopped converting would show its literal name.
//! The Shortcodes column protects the names with inline code so they stay
//! readable. Data comes from the `emojis` crate — the same crate (and, via
//! Cargo.lock, the same version) comrak's `shortcodes` feature resolves, so
//! the table cannot drift from what actually renders.
//!
//! Refresh the page with:
//!
//! ```bash
//! sed -i '' '/^## All shortcodes/,$d' docs/authoring/emoji.md
//! cargo run -p khb-core --example emoji-table >> docs/authoring/emoji.md
//! ```

use std::collections::BTreeMap;

fn main() {
    // Group -> rows of (first shortcode, all shortcodes). Iteration inside a
    // group follows the crate's (Unicode CLDR) ordering.
    let mut groups: BTreeMap<String, Vec<(String, Vec<String>)>> = BTreeMap::new();
    let mut order: Vec<String> = Vec::new();
    for e in emojis::iter() {
        let mut codes = e.shortcodes();
        let Some(first) = codes.next() else {
            continue; // no shortcode -> not writable in Markdown, skip
        };
        let all: Vec<String> = std::iter::once(first)
            .chain(codes)
            .map(|s| format!("`:{s}:`"))
            .collect();
        let g = format!("{:?}", e.group());
        if !groups.contains_key(&g) {
            order.push(g.clone());
        }
        groups
            .entry(g)
            .or_default()
            .push((format!(":{first}:"), all));
    }

    // "SmileysAndEmotion" -> "Smileys & emotion"
    let title = |g: &str| -> String {
        let mut out = String::new();
        for (i, c) in g.chars().enumerate() {
            if c.is_uppercase() && i > 0 {
                out.push(' ');
                out.push(c.to_ascii_lowercase());
            } else {
                out.push(c);
            }
        }
        out.replace(" and ", " & ")
    };

    println!("## All shortcodes");
    println!();
    println!("Every shortcode the compiler understands, in Unicode (CLDR) order — where an emoji");
    println!("has several names, any of them works. The Emoji column is written *as shortcodes*");
    println!("in this page's source and converted at build time, so the table is also living");
    println!(
        "proof of the conversion. (Generated by `cargo run -p khb-core --example emoji-table`.)"
    );
    for g in &order {
        println!("\n### {}\n", title(g));
        println!("| Emoji | Shortcodes |");
        println!("|-------|------------|");
        for (bare, codes) in &groups[g] {
            println!("| {bare} | {} |", codes.join(" "));
        }
    }
}
